spring.application.name=knowledge-base

# Clé secrète (devrait être une chaîne longue et complexe en production)
jwt.secret=MaCleSecreteTresLongueEtComplexe1234567890

# Durée de validité du token d'accès (en millisecondes) ? ici 15 minutes
jwt.expiration=900000

# Durée de validité du refresh token (en millisecondes) ? ici 7 jours
jwt.refreshExpiration=604800000

spring.datasource.url=jdbc:postgresql://localhost:5432/plateforme_connaissance
spring.datasource.username=webadmin
spring.datasource.password=0000 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
