spring.application.name=knowledge-base

# Clé secrète (devrait être une chaîne longue et complexe en production) Elle fait 64 caractères ? donc parfaite pour HS512.
jwt.secret=SKNB3uTYcQ2uYGqHaD9p7k3K0m4rLpQWnEjL2M1oN7VbZp6QaXFtUdCvR7JkLzTY


# Durée de validité du token d'accès (en millisecondes) ? ici 15 minutes
jwt.expiration=900000

# Durée de validité du refresh token (en millisecondes) ? ici 7 jours
jwt.refreshExpiration=604800000

# Configuration de la base de données
spring.datasource.url=jdbc:postgresql://localhost:5432/plateforme_connaissance
spring.datasource.username=webadmin
spring.datasource.password=0000
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.flyway.locations=classpath:db/migration
spring.flyway.enabled=false

logging.level.org.springframework.security=DEBUG










